---
# tasks file for jenkins

- name: Import Jenkins GPG key 
  rpm_key:  
    state: present 
    key: https://pkg.jenkins.io/redhat/jenkins.repo 

- name: Add Jenkins repository 
  yum_repository: 
    name: jenkins 
    description: jenkins repository 
    baseurl: http://pkg.jenkins.io/redhat 
    enabled: no 
    gpgcheck: yes 

- name: Install Jenkins 
  yum: 
    name: jenkins
    enablerepo: jenkins 
    state: present 

- name: Start Jenkins 
  service: 
    name: jenkins-2.249
    enabled: yes 
    state: started 
